Traceback (most recent call last):
  File library/python/runtime_py3/test/traceback/crash.py:44 in main
    one()
  File library/python/runtime_py3/test/traceback/crash.py:12 in one
    modfunc(two)  # aaa
  File library/python/runtime_py3/test/traceback/mod/__init__.py:3 in modfunc
    f()  # call back to caller
  File library/python/runtime_py3/test/traceback/crash.py:16 in two
    three(42)
  File library/python/runtime_py3/test/traceback/crash.py:20 in three
    raise RuntimeError('Kaboom! I\'m dead: {}'.format(x))
RuntimeError: Kaboom! I'm dead: 42

