Traceback (most recent call last):
  File "<string>", line XXX, in <module>
  File "library/python/runtime/importer.pxi", line XXX, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line XXX, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "library/python/runtime/test/traceback/__main__.py", line XXX, in <module>
    main()
  File "library/python/runtime/test/traceback/crash.py", line XXX, in main
    one()
  File "library/python/runtime/test/traceback/crash.py", line XXX, in one
    modfunc(two)  # aaa
  File "library/python/runtime/test/traceback/mod/__init__.py", line XXX, in modfunc
    f()  # call back to caller
  File "library/python/runtime/test/traceback/crash.py", line XXX, in two
    three(42)
  File "library/python/runtime/test/traceback/crash.py", line XXX, in three
    raise RuntimeError('Kaboom! I\'m dead: {}'.format(x))
RuntimeError: Kaboom! I'm dead: 42

